services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"  
      - "9000:9000" 
